### PR TITLE
[WIP] FIX: flaky CI testBufferFull failure

### PR DESCRIPTION
**Pull request by chenqi0805**
*Issue #, if available:*
#221 

*Description of changes:*
Introduce retry with default backoff on test GRPC client to handle request failure.

PS: will run CI for quite a few times to see if it works.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chenqi0805** [comment]
The flaky test still fails. Need to investigate further.

**Comment by chenqi0805** [comment]
Will use this PR to do some debugging.

**Comment by kowshikn** [comment]
I have a feeling this has to do with CI environment. Let me take a look at this and see if we can isolate it.

**Comment by chenqi0805** [comment]
@kowshikn Sure. Thanks. Just remind you I posted the full trace in the issue #221

**Comment by chenqi0805** [comment]
Closed as already obtained a full traceback.

**Pull request closed without merging**
