### PR TITLE
MAINT: implement shutdown API and remove stop method in ElasticsearchSink

### PR DESCRIPTION
**Pull request by chenqi0805**
*Issue #, if available:*

*Description of changes:*
Following the latest change in data-prepper-api, moved logic from stop() to shutdown()

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by AustinTag — APPROVED** [review]
LGTM

**Comment by kowshikn** [comment]
@chenqi0805 Did you run it locally and test the shutdown? I want to make sure this works :)

**Comment by chenqi0805** [comment]
> @chenqi0805 Did you run it locally and test the shutdown? I want to make sure this works :)

Will do. Thanks for reminder.

**Comment by chenqi0805** [comment]
@kowshikn Made some tweaks in example config file. Shutdown cleanly by `curl localhost:9400`:
```
./data-prepper-jdk-v0.7.0-alpha-macos-x64/data-prepper-tar-install.sh /Users/qchea/IdeaProjects/simple-ingest-transformation-utility-pipeline/examples/trace_analytics_no_ssl.yml
...
3235 [main] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [raw-pipeline] - Initiating pipeline execution
3236 [main] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [raw-pipeline] - Submitting request to initiate the pipeline processing
3237 [main] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [service-map-pipeline] - Initiating pipeline execution
3237 [main] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [service-map-pipeline] - Submitting request to initiate the pipeline processing
3237 [main] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [entry-pipeline] - Initiating pipeline execution
3345 [service-map-pipeline-process-worker-2-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker  –  service-map-pipeline Worker: No records received from buffer
4593 [main] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [entry-pipeline] - Submitting request to initiate the pipeline processing
4696 [entry-pipeline-process-worker-1-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker  –  entry-pipeline Worker: No records received from buffer
6243 [raw-pipeline-process-worker-3-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker  –  raw-pipeline Worker: No records received from buffer
68206 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [raw-pipeline] - Received shutdown signal with timeout 5000, will initiate the shutdown process
68210 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [raw-pipeline] - Shutting down process workers
69294 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [service-map-pipeline] - Received shutdown signal with timeout 5000, will initiate the shutdown process
69302 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [service-map-pipeline] - Shutting down process workers
69308 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [entry-pipeline] - Received shutdown signal with timeout 5000, will initiate the shutdown process
71376 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.Pipeline  – Pipeline [entry-pipeline] - Shutting down process workers
71483 [HTTP-Dispatcher] INFO  com.amazon.dataprepper.pipeline.server.DataPrepperServer  – Data Prepper server stopped
```

**Review by kowshikn — APPROVED** [review]

**Pull request merged**
