### PR TITLE
Added initial EC2 CFN template.

### PR DESCRIPTION
**Pull request by wrijeff**
*Description of changes:*

Adding initial CFN template. Tested against a public AWS ES instance with an IAM role access policy. Still need to test w/ VPC, and potentially update the Data Prepper config default values.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by laneholloway — COMMENTED** [review]
This looks good, do we expect to provide more stringent constraints on many of the parameters?

**Comment by wrijeff** [comment]
> This looks good, do we expect to provide more stringent constraints on many of the parameters?

Ah good point, I glossed over the parameters early on just to get the template working. Can easily add some better validation while this PR is still out for review.

**Review by kowshikn — APPROVED** [review]
> > This looks good, do we expect to provide more stringent constraints on many of the parameters?
> 
> Ah good point, I glossed over the parameters early on just to get the template working. Can easily add some better validation while this PR is still out for review.

Not sure what validations we can do with existing parameters. Otherwise this LGTM for the first version. `cfn-hup` should be included in the next version or release, as thats more useful.

**Review by laneholloway — APPROVED** [review]
For the first version this is fine, but there are simple validations we can do to ensure a true http/s address, etc. in the future.

**Comment by wrijeff** [comment]
> > > This looks good, do we expect to provide more stringent constraints on many of the parameters?
> > 
> > 
> > Ah good point, I glossed over the parameters early on just to get the template working. Can easily add some better validation while this PR is still out for review.
> 
> Not sure what validations we can do with existing parameters. Otherwise this LGTM for the first version. `cfn-hup` should be included in the next version or release, as thats more useful.

+1 cfn-hup, saw that in other templates but deprioritized it for this initial version.

Re: validation - I'll be publishing a commit w/ regexes to ensure the fields match up with their types (e.g. ES endpoint starts with https://, IAM roles only contain allowed characters, etc.)

**Pull request merged**
